### PR TITLE
Yaml example

### PR DESCRIPTION
**Pull request by Mano-Rom**
Add an example yaml file and model, that implement the input output parameters and state.

### CODE REVIEW

**Review by manuGil — APPROVED** [review]

**Comment by manuGil** [comment]
@Mano-Rom  and @mcvetkov 
Using Mano's example, I came to this format for the configuration file. Notice that I remove the `path` keyword because I think we an consider that as part of the 'set up' and model registration. In my opinion (which can be debated), a user can be interested in running simulations on a PC, in which case the user shouldn't have to set the path to the models because the path is Illumator installation itself. Or a user can run simulations on a RasPi Cluster, it would be better if setting paths to the models is part of the cluster set up. 

```yaml
scenario: ExampleScenario # in mosaik so called world
scenario_data: '' #path to the scenario data file ()
start_time: '2012-01-02 00:00:00' # ISO 8601 start time of the simulation
end_time: 10 # duration in seconds 
nodes: # list of node for the grid network t
- name: Battery1 # name for the node
  model: BatteryModel # name of the model registered in the Illuminator
  Inputs: [demand_power_flow=0] 
  Outputs: [effective_power_flow=0, soc=None]
  Parameters: [charge_power_max=100, discharge_power_max=200, soc_min=0.1, soc_max=0.9, capacity=1000]
  States: [initial_soc=0.5]
- name: Battery2
  model: BatteryModel # nodes can reuse the same model
  Inputs: [demand_power_flow=0] 
  Outputs: [effective_power_flow=0, soc=None]
  Parameters: [charge_power_max=100, discharge_power_max=200, soc_min=0.1, soc_max=0.9, capacity=5000]
  States: [initial_soc=0.5]
- name: PV1
  model: PVModel
  Inputs: [demand_power_flow=0] 
  Outputs: [effective_power_flow=0, soc=None]
  Parameters: [charge_power_max=100, discharge_power_max=200, soc_min=0.1, soc_max=0.9, capacity=1000]
  States: [initial_soc=0.5]
connections:
- from: Battery1 # start node
  to: Battery2 # end node
  values: !!pairs # a list values to be exchanged between the nodes
    - val1: val2 # output of 'from node': input of 'to node'
    - val3: val4 
- from: PV 
  to: Battery2 
  data: !!pairs # using the generic 'data' keyword to define what it is exchanged between the nodes
    - val1: val2
    - val3: val4
 ```

**Comment by manuGil** [comment]
I implemented the yamls strucure I mentioned above, and also created an schema for validation. The changes are in this PR: https://github.com/Illuminator-team/Illuminator/pull/28/commits/eeb37b1e825c8645809f3a0ae472cd31ae7a64fa

**Comment by manuGil** [comment]
After a discussion with @jgrguric96, we think it will be better if the top items in the configuration file are nested under scenario. For example:

```yaml
scenario:
  name: "ExampleScenario" # in mosaik so called world
  scenario_data: 'path/to/file' #path to the scenario data file ()
  start_time: '2012-01-02 00:00:00' # ISO 8601 start time of the simulation
  end_time: 10 # duration in seconds 
nodes:
...
```
I reflected this in the `modelling-example.yaml` and its schema in #28

**Comment by jgrguric96** [comment]
Notes post meeting (W.I.P.):

- Change name from 'nodes' back to 'models'. Change 'model' to 'type'.
Turns into: `models: \n name: Battery1 \n type: BatteryModel \n`
- There was a misunderstanding on what `val1:val2` means. Manuel explained that they represent an `from:to` connection
- They prefer the [separate nesting](https://github.com/Illuminator-team/Illuminator/pull/37#issuecomment-2342974570) of "scenario" from "models" and "connections"
- There was curiosity if the `from:to` connections could become ambiguous so that it can be structured it any way.
- Monitoring/Collector is a logger. Milos does not want it to be considered a model. See Manuel's comment above.

**Pull request merged**
